### ISSUE TITLE
Write about discovery of Reinforcement Learning models including Soft Actor-Critic (SAC)

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#112]
# Description

This story is about doing research over Soft Actor-Critic and documenting it on the wiki.

# Why do we need to do this?

This story is needed for getting the know how Soft Actor-Critic works.

# Tasks for this user story 

- [x] Describe the types of models
- [x] Write a conclusion about the model choice

# Acceptance criteria

This user story is done when there is enough documented about this subject on the wiki

**Comment by Max2411** [comment]
Small changes for this issue @RichardDev01. Maybe check with others of the AI team.
- Research about different models using SAC -> Write short explanations over Reinforcement Learning models, including SAC
- Make a table about the different models -> Table of pro/con's from each model
- Write a conclusion about the research -> Write a conclusion about the model choice

**Comment by RichardDev01** [comment]
@Max2411 , when the story is under review, add the wiki page in the comment section of the issue
https://github.com/HU-ICT-LAB/RobotWars/wiki/Reinforcement-Learning-Models
