### ISSUE TITLE
Make connection between server and robot

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#129]
# Description

This story is about making a connection between the server and the robot

# Needed stories before this

[#128 ](https://github.com/HU-ICT-LAB/RobotWars/issues/128)

# Why do we need to do this?

With this story we want to achieve the ability to upload policy files from the server to the jetson.

# Tasks for this user story 

- [ ] Create api
- [ ] Create functionality for retreiving policy on jetson
- [ ] Update this wiki page: https://github.com/HU-ICT-LAB/RobotWars/wiki/Connect-the-robomaster-to-the-server

# Acceptance criteria

This user story is done when there is a connection between the server and the S1

**Comment by Rubenvdbrink** [comment]
@RichardDev01 Add the reason "With this story we want to achieve the ability to upload policy files from the server to the jetson." to heading 2

**Comment by Rubenvdbrink** [comment]
@RichardDev01 Maybe add that this story is following after story #128
