### ISSUE TITLE
Learn how the RoboMasters can communicate with eachother. 

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#13]
# Description

When we are going to introduce teamplay the robots need to communicate with eachother to use strategies. 

# Why do we need to do this?

This story is needed for understanding if there is a possibility of communication between the robots. We could use that information to creating events that require comunication between the robots.

# Tasks for this user story 

- [ ] Research if the robomasters can communicate locally with eachother. 
- [ ] Research if multiple robomasters can communicatie with eachother via the server.

# Acceptance criteria

This story is done when the research topic above has been done and documented on the wiki

**Comment by RichardDev01** [comment]
This userstory is basically done right? @SwagLag , can you confirm this because i know there are a few wiki pages about it
