### ISSUE TITLE
Create components in webapp for all backend functionalities

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#133]
# Description

This story is about creating components for the webapp for all backend functionalities 

# Why do we need to do this?

This story is need for creating components for the webapp

# Tasks for this user story 

- [x] Find out which components we need
- [x] Create components in React

# Acceptance criteria

This user story is done when we got all the components we need in the webapp.

**Comment by Rubenvdbrink** [comment]
Homepage:
- Navigatie bar(Home, Start Game, Game overview)
- Vak met informatie over robot en boven dat vak een selectiemenu voor de robot.
- Vak voor live camera feed van geselecteerde robot.

Start game page:
- Navigatie bar
- Vak met in te stellen instellingen voor de game die je wilt maken
- Submit knop

**Comment by Rubenvdbrink** [comment]
note: I used react-router-dom (install with npm i -D react-router-dom) for the page routing

**Comment by Rubenvdbrink** [comment]
color pallette used: https://colorhunt.co/palette/2121213232320d737714ffec
