### ISSUE TITLE
Code restructure

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#160]
# Description

As developers, we want to have a clear project structure and accomplish an easy installation process. We’ll do this by separating the project in folders by the machine it will get installed on, so with installation users can choose which machine is getting installed and only the relevant code will be installed.

# Why do we need to do this?

This story is needed for easy installation of the requirements for the code you are going to use.

# Tasks for this user story 

- [x] splits code in folder
- [x] update installation process
- [x] update readme

# Acceptance criteria

This user story is done when the code is split in folders, the installation process is adapted to this change and the readme is updated.

**Comment by RichardDev01** [comment]
@Lucas-vdr-Horst , This is done right? i saw a pull request for restructure code

**Comment by Lucas-vdr-Horst** [comment]
Yeah sorry forgot to update, thanks for doing
