### ISSUE TITLE
RoboMaster Hit Detection (Shelved)

### ISSUE THREAD

**Issue by SwagLag** [HU-ICT-LAB/RobotWars#22]
# Description

This story is about enabling robots to detect when they have hit another robot.

# Tasks for this user story 

- [ ] Task 1 
- [ ] Task 2
- [ ] Task 3

# Definition of done

As product owner I want that the robots are capable of registering when they are hit and when they are hitting a robot to benefit the reinforcement learning process

**Comment by RichardDev01** [comment]
Shelved Userstory
