### ISSUE TITLE
Anti Cheat (Shelved)

### ISSUE THREAD

**Issue by SwagLag** [HU-ICT-LAB/RobotWars#23]
# Description

This story is about implementing an anti-cheat to prevent outsider influence from affecting the robot's scoring mechanism

# Tasks for this user story 

- [ ] Task 1 
- [ ] Task 2
- [ ] Task 3

# Definition of done

As product owner I want the robots to be unaffected by harmful outsider influence which could be detrimental to hosting (automated) competition

**Comment by RichardDev01** [comment]
Shelved user story
