### ISSUE TITLE
Roomba baseline moving algorithm

### ISSUE THREAD

**Issue by SwagLag** [HU-ICT-LAB/RobotWars#69]
# Description

This story is about realising a standard moving method for the RoboMaster S1. We intend to replicate the way a Roomba moves around the room to get a first moving algorithm.

# Why do we need to do this?

This story is needed to realise a baseline method for moving around the robot autonomously. By completing this
user story, we hope to gain some insight into how to create an intelligent agent which can move around autonomously.

# Tasks for this user story 

- [ ] Impact detection
- [ ] Condition-based turning
- [ ] Testing

# Acceptance criteria

This user story is done when the robot rotates sufficiently on collision so it can continue moving without great impediment.

**Comment by SwagLag** [comment]
Issue failed: We couldn't find *any* method to detect collision events.

**Comment by RichardDev01** [comment]
Maybe we can do this again when we add extra hardware but for now this Issue is closed
