### ISSUE TITLE
Design AI hub framework

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#91]
# Description

This story is about designing the AI hub workflow/framework

# Why do we need to do this?

This story is needed for a guided process to create and deploy our own ai on the S1

# Tasks for this user story 

- [x] Create a workflow from experience to policy with pseudo code
- [ ] ~Code the desired workflow from made pseudo code~

# Acceptance criteria

This user story is done when there is a workflow in the AI Hub that takes experience and returns a policy

**Comment by RichardDev01** [comment]
@SwagLag can you make a wiki page about the frame work, then this story is done

**Comment by SwagLag** [comment]
@RichardDev01 wiki page is done, https://github.com/HU-ICT-LAB/RobotWars/wiki/Experience-to-Policy-Framework . Let me know if I can close this issue.

**Comment by RichardDev01** [comment]
@SwagLag , can you add the diagram you worked out? then the issue should be done

**Comment by SwagLag** [comment]
@RichardDev01 Diagram is in, it's currently located on the workflow branch but it's available now in the wiki page.

**Comment by RichardDev01** [comment]
alright, this US is done
